export interface Contact {
	company: string,
	department: string,
	displayName: string,
	emailAddresses: Array<any>,
	familyName: string,
	givenName: string,
	hasThumbnail: boolean,
	imAddresses: Array<any>,
	jobTitle: string,
	middleName: string,
	note: string,
	phoneNumbers: Array<any>,
	postalAddresses: Array<any>,
	prefix: any,
	rawContactId: string,
	recordID: string,
	suffix: any,
	thumbnailPath: string,
	urlAddresses: Array<any>,
}
